name: 'dbt_scdtype2_demo'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_scdtype2_demo:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
